name: first-workflow
on:
  pull_request:
    branches:
      - main

jobs:
  upload-test-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: echo $PR_NUMBER > /tmp/pr_number.txt

      - name: Debug
        run: ls

      - uses: actions/upload-artifact@v6
        with:
          name: metadata
          path: /tmp/pr_number.txt